-- logger.debug('Inserting consumable and currency item data...');
INSERT INTO items (name, description, category, collection_target, required_level, usage_details) VALUES ('회복 물약', '체력을 회복하는 물약', '물약', NULL, 0, '체력 회복');
INSERT INTO items (name, description, category, collection_target, required_level, usage_details) VALUES ('모험가의 엠블럼', '기본 엠블럼, 장착 시 능력치 소폭 증가', '엠블럼', NULL, 0, '장비');
INSERT INTO items (name, description, category, collection_target, required_level, usage_details) VALUES ('투박한 트리플퀴즈', '투박한 퀴즈 아이템', '기타', NULL, 0, '아이템');

INSERT INTO items (name, description, category, collection_target, required_level, usage_details) VALUES
('강화 물약', '능력을 일시적으로 강화하는 물약', '물약', NULL, 5, '능력치 증가'),
('활력의 붉은 열매', '피로도를 회복시키는 열매', '회복 아이템', NULL, 0, '피로도 회복');

-- 새로운 소비 물약 및 기타 아이템들
INSERT INTO items (name, description, category, collection_target, required_level, usage_details) VALUES
('체력 포션', 'HP 즉시 회복', '물약', NULL, 0, 'HP 즉시 회복'),
('자동 회복 물약', 'HP 50% 이하시 자동 사용, HP 회복', '물약', NULL, 0, 'HP 50% 이하시 자동 사용, HP 회복'),
('붕대', '전투 중 HP 빠른 회복', '회복 아이템', NULL, 0, '전투 중 HP 빠른 회복'),
('불사의 가루', '사망 시 즉시 부활, 필드 보스/던전 필수', '특수 아이템', NULL, 0, '사망 시 즉시 부활, 필드 보스/던전 필수'),
('여행자 간식', '체력 50% 증가, 일일 미션 소모', '음식', NULL, 0, '체력 50% 증가, 일일 미션 소모'),
('사과 수플레', '체력/스태미나/능력치 일시 증가, 미션 소모', '음식', NULL, 0, '체력/스태미나/능력치 일시 증가, 미션 소모'),
('감자수프', '체력/스태미나/능력치 일시 증가, 미션 소모', '음식', NULL, 0, '체력/스태미나/능력치 일시 증가, 미션 소모'),
('치명타 비약', '일정 시간 치명타 확률 증가', '물약', NULL, 0, '일정 시간 치명타 확률 증가'),
('궁극기 비약', '일정 시간 궁극기 게이지 증가 속도 상승', '물약', NULL, 0, '일정 시간 궁극기 게이지 증가 속도 상승'),
('고급 연금술 촉매', '장비 강화, 연금술 재연소에 사용', '재료', NULL, 0, '장비 강화, 연금술 재연소에 사용'),
('레어 연금술 촉매', '고급 장비 강화, 연금술 재연소에 사용', '재료', NULL, 0, '고급 장비 강화, 연금술 재연소에 사용'),
('마법 유탄(화염)', '화염 속성 공격력 일시 상승', '물약', NULL, 0, '화염 속성 공격력 일시 상승'),
('마법 유탄(번개)', '번개 속성 공격력 일시 상승', '물약', NULL, 0, '번개 속성 공격력 일시 상승'),
('마법 유탄(바람)', '바람 속성 공격력 일시 상승', '물약', NULL, 0, '바람 속성 공격력 일시 상승'),
('마법 유탄(산성)', '산성 속성 공격력 일시 상승', '물약', NULL, 0, '산성 속성 공격력 일시 상승'),
('불꽃의 결정', '연금술/강화/특수 제작에 사용', '재료', NULL, 0, '연금술/강화/특수 제작에 사용'),
('얼음의 결정', '연금술/강화/특수 제작에 사용', '재료', NULL, 0, '연금술/강화/특수 제작에 사용'),
('전기의 결정', '연금술/강화/특수 제작에 사용', '재료', NULL, 0, '연금술/강화/특수 제작에 사용'),
('광휘의 결정', '연금술/강화/특수 제작에 사용', '재료', NULL, 0, '연금술/강화/특수 제작에 사용'),
('봉인의 결정', '연금술/강화/특수 제작에 사용', '재료', NULL, 0, '연금술/강화/특수 제작에 사용'),
('펫 먹이', '펫 친밀도/스태미나 회복, 펫 관리', '음식', NULL, 0, '펫 친밀도/스태미나 회복, 펫 관리'),
('사과 주스', '요리, 교환, 펫 관리', '음식', NULL, 0, '요리, 교환, 펫 관리'),
('조개찜', '요리, 교환, 미션', '음식', NULL, 0, '요리, 교환, 미션'),
('감자 샐러드', '요리, 교환, 미션', '음식', NULL, 0, '요리, 교환, 미션'),
('연금술 부스러기', '고급 아이템 제작 및 교환', '재료', NULL, 0, '고급 아이템 제작 및 교환');

-- 새로운 엠블럼/룬 아이템들
INSERT INTO items (name, description, category, collection_target, required_level, usage_details) VALUES
('현란함', '치명타 확률 10% 증가, 치명타 피해 30% 증가', '룬', NULL, 0, '1티어'),
('지혜로움', '모든 스킬 쿨타임 18% 감소', '룬', NULL, 0, '1티어'),
('여신의 가호', '전투 시작/궁극기 사용 시 30초간 피해 25% 증가', '룬', NULL, 0, '1티어'),
('깨달음', '클래스 레벨 40 이상 시 공격력 6% 증가, 65 이상 시 추가 4% 증가', '룬', NULL, 0, '1티어'),
('마나 격류', '스킬 사용 시 5초간 공격력 3.5% 증가, 최대 4중첩', '룬', NULL, 0, '1티어'),
('바위 거인', '강타 적중 시 공격력 3% 증가(최대 3중첩), 3중첩 시 5초간 공격력 20% 증가', '룬', NULL, 0, '1티어'),
('엄습하는 그림자', '연타 적중 시 764의 지속 피해, 10초간 피해 3% 증가(최대 3중첩, 재사용 0.5초)', '룬', NULL, 0, '1티어'),
('안정+', '체력 75% 이상일 때 피해 11% 증가', '룬', NULL, 0, '1티어'),
('굳건함+', '퍼스트 어택 적중 시, 15초마다 공격력·방어력 1%씩(최대 10중첩)', '룬', NULL, 0, '2티어'),
('날쌤+', '강타 적중 시 5초간 연타 피해 18% 증가', '룬', NULL, 0, '2티어'),
('강렬함+', '연타 적중 시 5초간 강타 피해 18% 증가', '룬', NULL, 0, '2티어'),
('광폭함+', '브레이크 피해 30% 증가, 무방비 피해 18% 증가', '룬', NULL, 0, '2티어'),
('냉혹함', '치명타 미적중 시 치명타 확률 12%씩 증가(치명타 적중 시 초기화)', '룬', NULL, 0, '2티어'),
('붉은 맹약', '공격 적중 시 10초간 공격력 18% 증가하는 룬 생성(룬 위에 있을 때, 재사용 15초)', '룬', NULL, 0, '2티어'),
('용병 왕', '주변 적 수 많을수록 피해 최대 12% 증가, 받는 피해 최대 6% 감소', '룬', NULL, 0, '2티어'),
('평원 방랑자', '이동 스킬 사용 시 10초간 피해 12%·이동속도 30% 증가', '룬', NULL, 0, '2티어'),
('비열한 일격', '카운터 적중 시 4초간 피해 24% 증가', '룬', NULL, 0, '2티어'),
('초기+', '전투 시작 시 30초간 피해 20% 증가', '룬', NULL, 0, '2티어'),
('폭풍+', '무방비 공격 적중 시 5초간 스킬·공격 속도 40% 증가', '룬', NULL, 0, '2티어'),
('저격+', '3초간 이동 없을 때 피해 15% 증가', '룬', NULL, 0, '2티어'),
('흡혈+', '출혈 적 공격 시 8초간 공격력 15% 증가(재사용 12초)', '룬', NULL, 0, '2티어'),
('원소술사', '화상/빙결/감전 적 공격 시 9초간 공격력 4% 증가(재사용 각 10초)', '룬', NULL, 0, '2티어'),
('메마른 땅', '자원 50% 미만 시 피해 9%, 추가타 확률 6% 증가', '룬', NULL, 0, '2티어'),
('은빛 첨탑', '아군 회복 시 15초간 피해 5% 증가(최대 3중첩, 재사용 5초)', '룬', NULL, 0, '2티어'),
('거센 소나기', '궁극기 사용 시 15초간 피해 30% 증가', '룬', NULL, 0, '2티어'),
('칼날 보루', '강타 적중 시 20%만큼 출혈 부여(전사 계열)', '룬', NULL, 0, '2티어'),
('응축된 마력', '자원 50% 미만 시 피해 15% 증가(마법사 계열)', '룬', NULL, 0, '2티어'),
('고요한 바람', '주변 3m 내 적 없을 때 피해 13% 증가(궁수 계열)', '룬', NULL, 0, '2티어'),
('신성한 수양', '보조 스킬 사용 시 10초간 공격력·회복력 4%(최대 3중첩, 힐러 계열)', '룬', NULL, 0, '2티어'),
('전율하는 악상', '파티 플레이 시 공격력 12% 증가(음유시인 계열)', '룬', NULL, 0, '2티어'),
('흉포한 의지', '피해 시 35% 확률로 궁극기 게이지 9 획득(재사용 3초)', '룬', NULL, 0, '2티어'),
('쇄빙', '빙결 적 공격 시 5초간 추가타 확률 10% 증가(재사용 3초)', '룬', NULL, 0, '2티어'),
('영구 동토', '전투 중 1초마다 4m 내 적에게 1668의 냉기 피해', '룬', NULL, 0, '2티어'),
('횃불', '화상 적 공격 시 5초간 치명타 확률 10% 증가(재사용 3초, 화염술사)', '룬', NULL, 0, '2티어'),
('격통+', '정신 적 공격 시 6m 내 적에게 5562의 정신 피해(재사용 5초)', '룬', NULL, 0, '3티어'),
('쇠약+', '중독 적 공격 시 7231의 추가 피해(재사용 5초)', '룬', NULL, 0, '3티어'),
('방호+', '받는 지속 피해 20% 감소', '룬', NULL, 0, '3티어'),
('생명+', '피해 시 9.9초간 방어력 0% 증가, 체력 1% 회복(최대 10중첩, 근거리)', '룬', NULL, 0, '3티어'),
('독 안개', '공격 시 4초간 독 안개 생성, 3m 내 적에게 1초마다 1390 중독 피해(재사용 4초)', '룬', NULL, 0, '3티어'),
('과충전', '궁극기 사용 시 10초간 1초마다 주변 적에게 6675 감전 피해', '룬', NULL, 0, '3티어'),
('검은 서약', '공격 시 10초간 보호의 룬 생성, 룬 위에 있으면 받는 피해 18% 감소(재사용 15초)', '룬', NULL, 0, '3티어'),
('끝없는 활력', '추가타 적중 시 체력 1.3% 회복(재사용 0.5초)', '룬', NULL, 0, '3티어'),
('제물+', '신성 적 공격 시 체력 230 회복(재사용 5초)', '룬', NULL, 0, '3티어'),
('반작용', '피해 시 50% 확률로 4m 내 적에게 2225 충격파 피해(재사용 0.5초)', '룬', NULL, 0, '3티어'),
('방랑 기사', '도발 시 체력 5% 보호막, 도발 적에게 정신·출혈 피해', '룬', NULL, 0, '3티어'),
('폭풍 구름', '15초마다 8m 내 적 최대 6명에게 벼락 22390 피해, 주변 적에도 2781 피해', '룬', NULL, 0, '3티어');

-- 새로운 재화 아이템들
INSERT INTO items (name, description, category, collection_target, required_level, usage_details) VALUES
('M캐시', '캐시샵 결제', '재화', NULL, 0, '캐시샵 아이템, 원석, 패키지 구매 등'),
('데카', '퀘스트, 거래소, 캐시샵 결제', '재화', NULL, 0, '캐시샵 아이템, 거래소, 던전 입장권 등'),
('패키지 포인트', '패키지 상품, 이벤트', '재화', NULL, 0, '패키지 포인트 전용 상품 구매'),
('캐시샵 포인트', 'M캐시 상품 구매 시 보상', '재화', NULL, 0, '캐시샵 포인트 전용 상품 구매'),
('미가공 데카 원석', '캐시샵, 패키지 상품', '재화', NULL, 0, '원석 연금술로 데카 획득'),
('미가공 골드 원석', '캐시샵, 패키지, 모험가 패스', '재화', NULL, 0, '원석 연금술로 골드 획득'),
('클래스 마스터 메달', '전직 퀘스트, 클래스 레벨 달성', '재화', NULL, 0, '엠블럼 구매, 클래스 변경'),
('갱신권', '사냥터, 던전, 심층 던전, 캐시샵(무료 상품)', '재화', NULL, 0, '상품 목록 갱신'),
('하트 토큰', '퀘스트, 업적, 아르바이트', '재화', NULL, 0, '여관 NPC 특별 아이템 교환, 가방 확장, 의상, 악기, 날개 등'),
('냥 토큰', '던전, 고양이 상인 뽑기', '재화', NULL, 0, '고양이 상인 아이템 교환'),
('은동전', '30분마다 1개 자동 충전, 퀘스트, 캐시샵', '재화', NULL, 0, '사냥터·던전 입장권(10~20개 소모), 일일/주간 콘텐츠 이용'),
('마족 공물', '12시간마다 1개 자동, 이벤트, 캐시샵', '재화', NULL, 0, '심층 던전 입장권(희귀), 고급 콘텐츠 입장'),
('심연의 화석', '어비스 던전 주간/타임어택 보상', '재화', NULL, 0, '전설 룬, 미스틱 다이스, 소원 항아리, 별의 인장 등 교환'),
('마물 퇴치 증표', '필드 보스 처치', '재화', NULL, 0, '각 마을 NPC에서 별의 인장, 강화 촉매 등 교환'),
('원정의 증거', '레이드 어려움 보스 처치(주간 1회)', '재화', NULL, 0, '전설 방어구/엠블럼 룬, 강화 촉매, 패션 장비 등 교환');

-- user_id 1번 사용자의 인벤토리에 추가 (수량 0)
INSERT INTO user_inventory (user_id, item_id, quantity) VALUES
(1, (SELECT id FROM items WHERE name = '체력 포션'), 0),
(1, (SELECT id FROM items WHERE name = '자동 회복 물약'), 0),
(1, (SELECT id FROM items WHERE name = '붕대'), 0),
(1, (SELECT id FROM items WHERE name = '불사의 가루'), 0),
(1, (SELECT id FROM items WHERE name = '여행자 간식'), 0),
(1, (SELECT id FROM items WHERE name = '사과 수플레'), 0),
(1, (SELECT id FROM items WHERE name = '감자수프'), 0),
(1, (SELECT id FROM items WHERE name = '치명타 비약'), 0),
(1, (SELECT id FROM items WHERE name = '궁극기 비약'), 0),
(1, (SELECT id FROM items WHERE name = '고급 연금술 촉매'), 0),
(1, (SELECT id FROM items WHERE name = '레어 연금술 촉매'), 0),
(1, (SELECT id FROM items WHERE name = '마법 유탄(화염)'), 0),
(1, (SELECT id FROM items WHERE name = '마법 유탄(번개)'), 0),
(1, (SELECT id FROM items WHERE name = '마법 유탄(바람)'), 0),
(1, (SELECT id FROM items WHERE name = '마법 유탄(산성)'), 0),
(1, (SELECT id FROM items WHERE name = '불꽃의 결정'), 0),
(1, (SELECT id FROM items WHERE name = '얼음의 결정'), 0),
(1, (SELECT id FROM items WHERE name = '전기의 결정'), 0),
(1, (SELECT id FROM items WHERE name = '광휘의 결정'), 0),
(1, (SELECT id FROM items WHERE name = '봉인의 결정'), 0),
(1, (SELECT id FROM items WHERE name = '펫 먹이'), 0),
(1, (SELECT id FROM items WHERE name = '사과 주스'), 0),
(1, (SELECT id FROM items WHERE name = '조개찜'), 0),
(1, (SELECT id FROM items WHERE name = '감자 샐러드'), 0),
(1, (SELECT id FROM items WHERE name = '연금술 부스러기'), 0),
(1, (SELECT id FROM items WHERE name = '현란함'), 0),
(1, (SELECT id FROM items WHERE name = '지혜로움'), 0),
(1, (SELECT id FROM items WHERE name = '여신의 가호'), 0),
(1, (SELECT id FROM items WHERE name = '깨달음'), 0),
(1, (SELECT id FROM items WHERE name = '마나 격류'), 0),
(1, (SELECT id FROM items WHERE name = '바위 거인'), 0),
(1, (SELECT id FROM items WHERE name = '엄습하는 그림자'), 0),
(1, (SELECT id FROM items WHERE name = '안정+'), 0),
(1, (SELECT id FROM items WHERE name = '굳건함+'), 0),
(1, (SELECT id FROM items WHERE name = '날쌤+'), 0),
(1, (SELECT id FROM items WHERE name = '강렬함+'), 0),
(1, (SELECT id FROM items WHERE name = '광폭함+'), 0),
(1, (SELECT id FROM items WHERE name = '냉혹함'), 0),
(1, (SELECT id FROM items WHERE name = '붉은 맹약'), 0),
(1, (SELECT id FROM items WHERE name = '용병 왕'), 0),
(1, (SELECT id FROM items WHERE name = '평원 방랑자'), 0),
(1, (SELECT id FROM items WHERE name = '비열한 일격'), 0),
(1, (SELECT id FROM items WHERE name = '초기+'), 0),
(1, (SELECT id FROM items WHERE name = '폭풍+'), 0),
(1, (SELECT id FROM items WHERE name = '저격+'), 0),
(1, (SELECT id FROM items WHERE name = '흡혈+'), 0),
(1, (SELECT id FROM items WHERE name = '원소술사'), 0),
(1, (SELECT id FROM items WHERE name = '메마른 땅'), 0),
(1, (SELECT id FROM items WHERE name = '은빛 첨탑'), 0),
(1, (SELECT id FROM items WHERE name = '거센 소나기'), 0),
(1, (SELECT id FROM items WHERE name = '칼날 보루'), 0),
(1, (SELECT id FROM items WHERE name = '응축된 마력'), 0),
(1, (SELECT id FROM items WHERE name = '고요한 바람'), 0),
(1, (SELECT id FROM items WHERE name = '신성한 수양'), 0),
(1, (SELECT id FROM items WHERE name = '전율하는 악상'), 0),
(1, (SELECT id FROM items WHERE name = '흉포한 의지'), 0),
(1, (SELECT id FROM items WHERE name = '쇄빙'), 0),
(1, (SELECT id FROM items WHERE name = '영구 동토'), 0),
(1, (SELECT id FROM items WHERE name = '횃불'), 0),
(1, (SELECT id FROM items WHERE name = '격통+'), 0),
(1, (SELECT id FROM items WHERE name = '쇠약+'), 0),
(1, (SELECT id FROM items WHERE name = '방호+'), 0),
(1, (SELECT id FROM items WHERE name = '생명+'), 0),
(1, (SELECT id FROM items WHERE name = '독 안개'), 0),
(1, (SELECT id FROM items WHERE name = '과충전'), 0),
(1, (SELECT id FROM items WHERE name = '검은 서약'), 0),
(1, (SELECT id FROM items WHERE name = '끝없는 활력'), 0),
(1, (SELECT id FROM items WHERE name = '제물+'), 0),
(1, (SELECT id FROM items WHERE name = '반작용'), 0),
(1, (SELECT id FROM items WHERE name = '방랑 기사'), 0),
(1, (SELECT id FROM items WHERE name = '폭풍 구름'), 0),
(1, (SELECT id FROM items WHERE name = 'M캐시'), 0),
(1, (SELECT id FROM items WHERE name = '데카'), 0),
(1, (SELECT id FROM items WHERE name = '패키지 포인트'), 0),
(1, (SELECT id FROM items WHERE name = '캐시샵 포인트'), 0),
(1, (SELECT id FROM items WHERE name = '미가공 데카 원석'), 0),
(1, (SELECT id FROM items WHERE name = '미가공 골드 원석'), 0),
(1, (SELECT id FROM items WHERE name = '클래스 마스터 메달'), 0),
(1, (SELECT id FROM items WHERE name = '갱신권'), 0),
(1, (SELECT id FROM items WHERE name = '하트 토큰'), 0),
(1, (SELECT id FROM items WHERE name = '냥 토큰'), 0),
(1, (SELECT id FROM items WHERE name = '은동전'), 0),
(1, (SELECT id FROM items WHERE name = '마족 공물'), 0),
(1, (SELECT id FROM items WHERE name = '심연의 화석'), 0),
(1, (SELECT id FROM items WHERE name = '마물 퇴치 증표'), 0),
(1, (SELECT id FROM items WHERE name = '원정의 증거'), 0);
-- logger.debug('Consumable and currency item data insertion complete.'); 